# These are supported funding model platforms

github: versx # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#patreon: # Replace with a single Patreon username
#custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
