site_name: MapJS
site_url: https://github.com/versx/MapJS
site_description: MapJS
site_author: versx

repo_url: https://github.com/versx/MapJS

theme:
  name: flatly

nav:
  - Home: 'index.md'
  - Install Guide:
    - Standard: install/standard.md
    - Docker: install/docker.md
  - Configuration:
    - Config: configuration/config.md
    - GeoJSON: configuration/geojson.md
    - Images: configuration/images.md
    - Locales: configuration/locales.md
  - Docs: documentation.md

markdown_extensions:
  - toc:
      permalink: '#'
      separator: "-"
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition

plugins:
    - search
